local chuck = require("chuck")
local packet = require("packet")

local buff = chuck.buffer.New()
local w = packet.Writer(buff)
w:WriteI8(1)
w:WriteI16(2)
w:WriteI32(3)
w:WriteStr("hello")
w:WriteStr("fasdfasdfasffdsafjklafklkfjklfjlkasfjaklfjfkjasfjaklf")
w:WriteStr("fasdfasdfasffdsafjklafklkfjklfjlkasfjaklfjfkjasfjaklf")

local r = packet.Reader(buff)

print(r:ReadI8())
print(r:ReadI16())
print(r:ReadI32())
print(r:ReadStr())
print(r:ReadStr())
print(r:ReadStr())